# Generated by Django 2.0.6 on 2018-07-05 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20180705_1305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title'], 'permissions': [('can_edit_book', 'Add,Del or Modify books')]},
        ),
    ]
